import Head from "next/head";
import Image from "next/image";
import Layout from "./../src/Layouts/main/Layout";
import { useEffect, useState } from "react";
import { PokemonCard } from "@/components/PokemonCard";
import { PokemonList } from "@/components/PokemonList/PokemonList";
import { getPokemons, getPokemonDetails } from "@/src/api";

import { setPokemons } from "@/src/actions";
import { useDispatch, useSelector } from "react-redux";


function Home() {

  const pokemons = useSelector((state) => state.pokemons)
  const dispatch = useDispatch()

  useEffect(() => {
    const fetchPokemons = async () => {
      const pokemonsRes = await getPokemons();
      const pokemonsDetails = await Promise.all(
        pokemonsRes.map((pokemon) => getPokemonDetails(pokemon))
      );
      dispatch(setPokemons(pokemonsDetails));
    };

    fetchPokemons();
  }, []);

  return (
    <>
      <Head>
        <title>Tiny Dex</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <PokemonList pokemons={pokemons} />
      </main>
    </>
  );
}

Home.getLayout = function getLayout(page) {
  return <Layout>{page}</Layout>;
};



export default Home;